### ISSUE TITLE
Inconsistent HTML syntax highlighting

### ISSUE THREAD

**Issue by jackjkal** [huacnlee/vscode-macos-classic.theme#2]
### Expected

HTML tags should have white (dark theme) or black (light theme) angle brackets.

### Actual

Some HTML tags (`<html>`, `<body>`, etc), as seen in the screenshot, lack the correct color for angle brackets.

<img width="645" alt="image" src="https://github.com/huacnlee/vscode-macos-classic.theme/assets/105620643/68c6281a-22b1-45a0-8085-918d35540fb2">

**Comment by huacnlee** [comment]
Just updated and released v1.6.1

<img width="1283" alt="image" src="https://github.com/huacnlee/vscode-macos-classic.theme/assets/5518/123d5a28-9555-4f89-b941-93dc4098d15b">
